export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export CLAUDE_CODE_OAUTH_TOKEN="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"
export CLAUDE_CODE_DISABLE_MOUSE=1